name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.0

    - name: Build
      run: go build -v ./...

    - name: Test
      run: mkdir /tmp/plugins && TFADD_E2E=1 TF_PLUGIN_CACHE_DIR=/tmp/plugins go test -v ./...
